### ISSUE TITLE
Syntax error when hacking on wit

### ISSUE THREAD

**Issue by Teruyuki-Matsuzaki** [wit-ai/node-wit#167] opened 2017-12-16 08:26 UTC
C:\Work\AI\wit.it\node-wit\lib\wit.js:36
      qs += '&junk=true');
                        ^

SyntaxError: Unexpected token )
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Work\AI\wit.it\node-wit\index.js:3:8)

**Comment by chessai** [comment] 2021-02-17 19:21
@Teruyuki-Matsuzaki this issue is really old, and I can't reproduce, so I'm going to close it. Please let me know if this is still an issue for you.

**Closed as completed by chessai** 2021-02-17 19:21 UTC
